/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
#pragma once
#include <iostream>

int sum = 0;

int Fibonacci( int pos, int& sum )
{
	if ( pos <= 1 )
	{
		return 1;
	}

	if ( pos == 2 )
	{
		return 1;
	}

	int f1 = 1;
	int f2 = 1;
	int f3 = 0;
	for( int index = 2; index <= pos; ++index )
	{
		f3 = f1 + f2;
		f1 = f2;
		f2 = f3;

		if ( f2 % 2 == 0 )
		{
			sum += f2;
		}
	}

	return f2;
}

int p2()
{
	int sum = 0;

	

	return sum;
}